baseURL = "https://tinygo.org/"
title = "TinyGo - Go on Microcontrollers and WASM"
languageCode = "en-us"
theme = "learn"

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "blue"
# Disable search function. It will hide search bar
disableSearch = true
editURL = "https://github.com/tinygo-org/tinygo-site/edit/release/content/"
disableInlineCopyToClipBoard = true

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
url = "https://github.com/tinygo-org/tinygo"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-book'></i> Godoc"
url = "https://pkg.go.dev/github.com/tinygo-org/tinygo?tab=doc"
weight = 20

[[menu.shortcuts]] 
name = "<i class='fab fa-twitter'></i> Twitter"
url = "https://twitter.com/TinyGolang"
weight = 30

[[menu.shortcuts]] 
name = "<i class='fab fa-slack'></i> Slack"
url = "https://gophers.slack.com/messages/CDJD3SUP6/"
weight = 40
