baseURL = "https://tinygo.org/"
title = "TinyGo"
languageCode = "en-us"
theme = "docsy"

enableGitInfo = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup.goldmark.renderer]
unsafe = true

# Everything below this are Site Params

[params]
copyright = "The TinyGo Authors"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "feba5f0a3db52897d"

# Enable Algolia DocSearch
algolia_docsearch = true

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/tinygo-org/tinygo-site"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/tinygo-org/tinygo"
github_branch= "release"


# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set the maximum number of menus to be displayed in the sidebar
sidebar_menu_truncate = 1000

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Mastodon"
	url = "https://mastodon.social/@TinyGo"
	icon = "fab fa-mastodon"
		desc = "Follow us on Mastodon to get the latest news!"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/TinyGolang"
	icon = "fab fa-twitter"
		desc = "You can also follow us on Twitter"
[[params.links.user]]
	name ="Go Pkg Docs"
	url = "https://pkg.go.dev/github.com/tinygo-org/tinygo?tab=doc"
	icon = "fa fa-book"
        desc = "Package Documentation"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/tinygo-org/tinygo"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://gophers.slack.com/messages/CDJD3SUP6/"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"

[params.mermaid]
enable = true
